version = 10000

type = '2x2'

data = 'setup'

name = 'Binary-Earth-Moon'

comment = 'test model'

time_yr = 0

ref = "None"

angles = 'relative'

# Earth-Moon
[binary.1]
name = 'Moon orbit'
an = 3.84e10
en = 0.0549
phase = 0.5
euler_deg = [ 0,  0, 0 ]

# Star binary
[binary.2]
name = 'Binary orbit'
an = 7.85389e12
en = 0
phase = 0.5
euler_deg = [ 0,  0, 0 ]

# outer binary
[binary.3]
name = 'Earth orbit'
an = 1.496e13
en = 0.01671
phase = 0.5
euler_deg = [ 0, 0, 0 ] # does not impact physics, only for plotting

#Earth
[star.1]
name = 'Earth'
euler_deg = [ 0,  72, 0 ]
M = 5.97e27
I = 2e55
S = 6.371e8
k = 0.008
Q = 1e5
Jn = 1.4e51

#Moon
[star.2]
name = 'Moon'
euler_deg = [ 0, -84, 0 ]
M = 7.348e25
I = 1.5e55
S = 1.737e8
k = 0.007
Q = 1e5
Jn = 1e51

#Sun 1
[star.3]
name = 'Star 1'
euler_deg = [ 0,  72, 0 ]
M = 1.0939e33
I = 2e55
S = 4.97426e10
k = 0.299
Q = 1e5
Jn = 1.4e51

#Sun 2
[star.4]
name = 'Star 2'
euler_deg = [ 0, -84, 0 ]
M = 8.9501e32
I = 1.5e55
S = 3.6872e10
k = 0.030
Q = 1e5
Jn = 1e51
