version = 10000

type = '2x2'

data = 'setup'

name = 'test'

comment = 'test model'

time_yr = 0

ref = "None"

angles = 'relative'

# first inner binary
[binary.1]
an = 2.9e12
en = 0.5
phase = 0.5
euler_deg = [ 0,  72, 0 ]

# second binary
[binary.2]
an = 3.8e10
en = 0.5
phase = 0.5
euler_deg = [ 180,  72, 0 ]

# outer binary
[binary.3]
an = 1.5e13
en = 0.5
phase = 0.5
euler_deg = [ 0, 0, 0 ] # does not impact physics, only for plotting

[star.1]
euler_deg = [ 0,  72, 0 ]
M = 9.9e32
I = 2e55
S = 4.1e10
k = 0.008
Q = 1e5
Jn = 1.4e51

[star.2]
euler_deg = [ 0, -84, 0 ]
M = 9.9e32
I = 1.5e55
S = 4.1e10
k = 0.007
Q = 1e5
Jn = 1e51

[star.3]
euler_deg = [ 0,  72, 0 ]
M = 6e27
I = 2e55
S = 6.4e8
k = 0.299
Q = 1e5
Jn = 1.4e51

[star.4]
euler_deg = [ 0, -84, 0 ]
M = 7e25
I = 1.5e55
S = 1.7e8
k = 0.030
Q = 1e5
Jn = 1e51
